# Generated by Django 4.2.1 on 2023-06-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_position_alter_teammember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='role',
            new_name='position',
        ),
    ]
