# Generated by Django 4.2.1 on 2023-06-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_standupcard_delete_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandupCard',
            new_name='Card',
        ),
    ]
