# Generated by Django 4.2.1 on 2023-06-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_standupcard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.teammember'),
        ),
    ]
