# Generated by Django 4.2.1 on 2023-06-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_card_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='member',
        ),
        migrations.RemoveField(
            model_name='card',
            name='position',
        ),
        migrations.RemoveField(
            model_name='card',
            name='remarks',
        ),
        migrations.AddField(
            model_name='card',
            name='blocker',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='complete',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='workingon',
            field=models.CharField(default=''),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.card')),
            ],
        ),
    ]
