# Generated by Django 4.2.1 on 2023-06-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remark_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.teammember'),
        ),
    ]
