# Generated by Django 4.2.1 on 2023-06-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_remark_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='blocker',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='complete',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='workingon',
            field=models.CharField(),
        ),
    ]
