# Generated by Django 4.2.1 on 2023-06-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_card_blocker_alter_card_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='blocker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='complete',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='workingon',
            field=models.CharField(max_length=100),
        ),
    ]
